version: '3'  
services: 
  web:
    build: . 
    ports: 
      - "3000:3000"
    volumes:
      - .:/app
    env_file:
      - .env/development/web.yml
      - .env/development/database.yml
  redis:
    image: redis
  database:
    image: postgres
    env_file:
      - .env/development/database.yml
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
